fragment ProductVariantDetailsFragment on ProductVariant {
  id
  name
  translation(languageCode: $locale) {
    id
    name
  }
  quantityAvailable
  attributes {
    ...SelectedAttributeDetailsFragment
  }
  pricing {
    onSale
    discount {
      gross {
        amount
        currency
      }
    }
    price {
      gross {
        ...PriceFragment
      }
    }
  }
}
